---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-dep
  labels: 
    app: database-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-tier
  
  template:
    metadata:
      labels:
        app: database-tier
    spec:
      containers:
      - name: mongodb-container
        image: mongo:4.4.6
        command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip"
            - "0.0.0.0"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        ports:
        - containerPort: 27017
